### ISSUE TITLE
Feature Request: Shapes with connectors.

### ISSUE THREAD

**Issue by Burrix** [fileformat-words/FileFormat.Words-for-.NET#18]
I would like to make shapes shuch as ovals and rectangles. Then I would like to connect them with arrows, which sticks to the shape. By "sticking" I mean that after moving the shape the end of the arrow reamians on the edge of the shape.

**Comment by sabir-aspose** [comment]
Group Shape feature provided in [v24.10.0](https://github.com/fileformat-words/FileFormat.Words-for-.NET/releases/tag/v24.10.0).

## Usage Source Code

```csharp
var doc = new FileFormat.Words.Document();
var body = new FileFormat.Words.Body(doc);
var diamond = new FileFormat.Words.IElements.Shape(0, 0, 200, 200,
                IElements.ShapeType.Diamond);
var oval = new FileFormat.Words.IElements.Shape(300, 0, 200, 200,
                IElements.ShapeType.Ellipse);
var groupShape = new FileFormat.Words.IElements.GroupShape(diamond, oval);
body.AppendChild(groupShape);
doc.Save("groupshapes-created-csharp.docx");
```
