### ISSUE TITLE
Standardizing Interfaces for Word Document Elements

### ISSUE THREAD

**Issue by sabir-aspose** [fileformat-words/FileFormat.Words-for-.NET#2]
A Word document comprises various elements, such as Paragraphs, Tables, Images, and more, positioned arbitrarily. Users require the ability to Insert, Remove, or Update any element at any position. Utilizing a unified interface allows all elements, irrespective of type, to be stored in a single collection with designated positions.

**Comment by sabir-aspose** [comment]
Resolved in [23.10.0](../releases/tag/v23.10.0). Now, all elements in a word document implement `IElement` interface defined in `FileFormat.Words.IElements` namespace. For more information, please check out classes and interfaces sections of [FileFormat.Words.IElements](https://fileformat-words.github.io/FileFormat.Words-for-.NET/api/FileFormat.Words.IElements.html) namespace.

The issue will be closed after more detailed documentation and examples.

**Comment by openize-words** [comment]
already resolved.
