### ISSUE TITLE
Enhance Font Size Handling in Run Object

### ISSUE THREAD

**Issue by sabir-aspose** [fileformat-words/FileFormat.Words-for-.NET#7]
Currently, font size is represented as a string, which stores the size as twice the value in Microsoft Word. To align with user expectations and Microsoft Word's behavior, we propose converting it to an integer. When retrieved via OpenXML SDK, it will be divided by 2, and when supplied to OpenXML SDK, it will be multiplied by 2, ensuring consistency for FileFormat.Words API users.

**Comment by openize-words** [comment]
already resolved.
