### ISSUE TITLE
Investigating Font Recognition Discrepancies in Microsoft Word

### ISSUE THREAD

**Issue by sabir-aspose** [fileformat-words/FileFormat.Words-for-.NET#8]
Even when applying a template, Microsoft Word sometimes fails to recognize fonts when supplied by the Run object, even in the absence of any apparent issues. To resolve this, we aim to investigate the matter by comparing the XML generated by Microsoft Word with that produced by OpenXML SDK.

**Comment by sabir-aspose** [comment]
Resolved in [23.10.0](../releases/tag/v23.10.0). The issue belonged to wrong appending sequence. Please give [Complexities of OpenXML SDK](https://fileformat-words.github.io/FileFormat.Words-for-.NET/articles/complexities.html) a read to develop insight to this and other similar issues.

The issue will be closed after adding more docs.

**Comment by openize-words** [comment]
already resolved.
